arohi/urls.py
from django.urls import path
from . import views

app_name = 'arohi'

urlpatterns = [
    # path('', views.order),

    path('', views.home, name='home_page',),

    path('contact', views.contact, name='contact_page'),

    path('feed/', views.feed, name='feed'),
    path('feed/<int:page>', views.feed, name='feed'),
    # path('feed/consumer/', views.consumer_feed, name='consumer_feed',),
    # path('feed/consumer/<int:page>', views.consumer_feed, name='consumer_feed',),
    # path('feed/investor/', views.investor_feed, name='investor_feed',),
    # path('feed/investor/<int:page>', views.investor_feed, name='investor_feed',),

    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('signup/', views.sign_up, name='signup'),


    path('dashboard/', views.dashboard, name='dashboard'),
    # path('dashboard/consumer', views.dashboard_consumer, name='consumer_dashboard'),
    # path('dashboard/investor', views.dashboard_investor, name='investor_dashboard'),
    # path('dashboard/entrepreneur', views.dashboard_entrepreneur, name='entrepreneur_dashboard'),

    path('product/add', views.add_product, name='add_product'),
    path('product/buy', views.buy_product, name='buy_product'),

    path('profiles/consumer', views.profile_consumer, name='profile_consumer'),
    path('profiles/entrepreneur', views.profile_entrepreneur, name='profile_entrepreneur'),
    path('profiles/investor', views.profile_investor, name='profile_investor'),
]

django_arohi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # Imported from webapp
    path('', include('arohi.urls')),

    # Default Configurations
    path('admin/', admin.site.urls)
]

arohi/models.py
from django.db import models


class User(models.Model):
    name = models.CharField(max_length=64)
    type = models.CharField(max_length=32)
    address = models.CharField(max_length=256)
    gender = models.CharField(max_length=16)

    @staticmethod
    def generate_fake(count=100):
        from random import seed, randint
        import forgery_py

        seed()

        for i in range(count):
            user = User(
                name=forgery_py.name.full_name(),
                type=0,
                gender='female',
                address=forgery_py.address.state(),
            )
            user.save()


class Investor(User):
    region = models.CharField(max_length=64)
    category_preference = models.TextField()
    investment_range_low = models.IntegerField()
    investment_range_hi = models.IntegerField()


class Entrepreneur(User):
    product_category = models.CharField(max_length=64)
    required_money = models.IntegerField()

    @staticmethod
    def generate_fake(count=100):
        from random import seed, randint
        import forgery_py

        seed()

        for i in range(count):
            user = Entrepreneur(
                # User=User.objects.get(id=randint(1, 50)),
                name=forgery_py.name.full_name(),
                type=0,
                gender='female',
                address=forgery_py.address.state(),
                required_money=(randint(5000, 15000)),
                product_category='silk'
            )
            user.save()


class Consumer(User):
    category_preference = models.TextField()


class Product(models.Model):
    Producer = models.ForeignKey(Entrepreneur, on_delete=models.CASCADE)
    cost_per_unit = models.IntegerField()
    funded_units = models.IntegerField()
    sales_goal = models.IntegerField()

    name = models.CharField(max_length=64)
    price = models.IntegerField()
    category = models.CharField(max_length=32)
    sold = models.IntegerField()
    quantity = models.IntegerField()
    discount = models.IntegerField()
    rating = models.FloatField()
    reviews = models.IntegerField()

    @staticmethod
    def generate_fake(count=100):
        from random import seed, randint
        import forgery_py

        seed()

        for i in range(count):
            product = Product(
                Producer=Entrepreneur.objects.filter(id=randint(100, 130)),
                name=forgery_py.name.industry(),
                sales_goal=(randint(10, 50)/10),
                cost_per_unit=(randint(10, 50)/10),
                funded_units=(randint(10, 50)/10),
                rating=(randint(10, 50)/10),
                reviews=randint(15, 100),
                price=randint(300, 5000),
                sold=randint(15, 50),
                quantity=randint(50, 100),
                discount=randint(1, 50),
                category='loom'
            )
            product.save()


class Investment(models.Model):
    Product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    Investor = models.ForeignKey(Investor, on_delete=models.CASCADE)
    amount = models.IntegerField()
    date = models.DateField()
    margin = models.IntegerField()
    units = models.IntegerField()

    @staticmethod
    def generate_fake(count=100):
        from random import seed, randint
        import forgery_py

        seed()

        for i in range(count):
            investment = Investment(
                Investor=Investor.objects.first(),
                Product_id=randint(1, 30),
                amount=randint(5000, 15000),
                margin=randint(5, 40),
                units=randint(40, 200),
                date=forgery_py.date.date()
            )
            investment.save()


class Order(models.Model):
    Buyer = models.ForeignKey(Consumer, on_delete=models.CASCADE)
    Product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    is_delivered = models.BooleanField()
    expected_delivery_date = models.DateField()

    @staticmethod
    def generate_fake(count=100):
        from random import seed, randint
        import forgery_py

        seed()

        for i in range(count):
            order = Order(
                Buyer_id=1,
                Product_id=randint(1, 20),
                quantity=randint(10, 50),
                is_delivered=randint(0, 1),
                expected_delivery_date=forgery_py.date.date()
            )
            order.save()

arohi/views.py
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.http import Http404
from arohi.models import *
from django import forms
from django.http import HttpResponse


def user_login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        next = request.GET.get('next')
        user = authenticate(request, username=username, password=password)
        print(user.username)
        if user:
            login(request, user)
            if next:
                return redirect(next)
            else:
                messages.success(request, "You have successfully logged in!")
                return redirect('arohi:feed')
        else:
            messages.error(request, "Provide valid credentials.")
            return render(request, 'auth/login.html')
    else:
        return render(request, 'auth/login.html')


@login_required
def user_logout(request):
    messages.success(request, "You have been logged out!")
    logout(request)
    return redirect('arohi:login')


def home(request):
    return render(request, 'index.html')


def contact(request):
    return render(request, 'contact.html')


def sign_up(request):
    return render(request, 'auth/signup.html')


@login_required
def feed(request, page=1):
    if request.user.username == 'consumer' or request.user.username == 'entrepreneur':
        return consumer_feed(request, page=page)
    elif request.user.username == 'investor':
        return investor_feed(request, page=page)


@login_required
def consumer_feed(request, page=1):
    print(request.user.username)
    try:
        product_list = Product.objects.all()
    except Product.DoesNotExist:
        raise Http404("Products does not exist.")

    # Shows 20 buyers per page
    pag = Paginator(product_list, 20)
    products = pag.get_page(page)
    return render(request, 'feed/consumer_feed.html', {'product_list': products, 'pagination': pag,
                                                       'page': page})


@login_required
def investor_feed(request, page=1):
    try:
        entrepreneur_list = Entrepreneur.objects.all()
    except Entrepreneur.DoesNotExist:
        raise Http404("Entrepreneurs don't exist in the database.")

    # Shows 20 buyers per page
    pag = Paginator(entrepreneur_list, 20)
    entrepreneurs = pag.get_page(page)
    return render(request, 'feed/investor_feed.html', {'entrepreneur_list': entrepreneurs, 'pagination': pag,
                                                       'page': page})


@login_required
def dashboard(request):
    if request.user.username == 'consumer':
        return dashboard_consumer(request)
    elif request.user.username == 'investor':
        return dashboard_investor(request)
    elif request.user.username == 'entrepreneur':
        return dashboard_entrepreneur(request)


@login_required
def dashboard_entrepreneur(request):
    user = Entrepreneur.objects.filter(id=114).first()
    context = {
        'products': Product.objects.filter(Producer=user).all()
    }
    return render(request, 'dashboard/entrepreneur.html', context=context)


@login_required
def dashboard_consumer(request):
    # Hard coded for sample
    user = Consumer.objects.first()
    products = Order.objects.filter(Buyer=user).order_by('expected_delivery_date').all()
    context = {
        'latest_delivery_date': products.first().expected_delivery_date,
        'bought_products': products.filter(is_delivered=False).all(),
        'delivered_products': products.filter(is_delivered=True).all()
    }
    return render(request, 'dashboard/consumer.html', context=context)


@login_required
def dashboard_investor(request):
    # Hard coded for sample
    user = Investor.objects.first()
    investments = Investment.objects.filter(Investor=user).all()
    context = {
        'investments': investments,
    }
    return render(request, 'dashboard/investor.html', context=context)


@login_required
def profile_entrepreneur(request):
    return render(request, 'profiles/entrepreneur.html')


@login_required
def profile_consumer(request):
    return render(request, 'profiles/consumer.html')


@login_required
def profile_investor(request):
    return render(request, 'profiles/investor.html')


@login_required
def add_product(request):
    return render(request, 'product/add.html')


@login_required
def buy_product(request):
    return render(request, 'product/buy.html')


class ContactForm(forms.Form):
    name = forms.CharField(max_length=64, required=True)
    email = forms.EmailField(max_length=64, required=True)
    messages = forms.CharField(widget=forms.Textarea)


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            return HttpResponse("Thanks for contacting us!")
    else:
        form = ContactForm()

    return render(request, 'contact.html', {'form': form})

arohi/templates/base.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Z-pack</title>

    {% block head %}
    {% endblock %}

    <style>
        * {
            box-sizing: border-box;
        }

        {% block styles %}
        {% endblock %}

    </style>
</head>
<body>

    <nav class="navbar navbar-expand navbar-dark bg-dark">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarText">
            <a class="nav-link" style="font-size: 35px; color: white">আরোহী</a>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item" style="margin: 0 15px">
                    <a class="nav-link" href="{% url 'arohi:home_page' %}">Home</a>
                </li>
                <li class="nav-item" style="margin: 0 15px">
                    <a class="nav-link" href="{% url 'arohi:feed' %}">Feed</a>
                </li>
                <li class="nav-item" style="margin: 0 15px">
                    <a class="nav-link" href="{% url 'arohi:dashboard' %}">Dashboard</a>
                </li>
                <li class="nav-item" style="margin: 0 15px">
                    <a class="nav-link" href="">Contact</a>
                </li>
            </ul>
            <a class="nav-link" style="color: white; letter-spacing: 1px" href="{% url 'arohi:profile_consumer' %}">
                {% if user.is_authenticated %}
                    {{ user.get_username }}
                {% else %}
                    Guest
                {% endif %}
            </a>
            <a class="btn btn-danger" href="{% url 'arohi:logout' %}">Logout</a>
        </div>
    </nav>

    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {% else %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {% endif %}
                <strong style="margin: 0 20%; text-align: center">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">
                            &times;
                        </span>
                    </button>
                </strong>
            </div>
        {% endfor %}
    {% endif %}

{% block body %}

    <div class="container">
        {% block content %}

        {% endblock %}
    </div>

{% endblock %}

</body>
</html>

arohi/templates/contact.html
{% extends 'base.html' %}

{% block content %}

    <h2>Contact Us</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
    </form>

{% endblock %}

arohi/templates/index.html
{% extends 'base.html' %}

{% block body %}
    {% load static %}
    <img src="{% static "/images/existence-is-pain.png" %}" class="img-fluid" alt="My Image" >

    <h1>Arohi!</h1>


{% endblock %}

arohi/templates/pagination_macro.html
<ul class="pagination justify-content-center" style="text-align: center">

    {# Loop which iterates through all the pages #}
    {% for p in pag.page_range %}
        {% if p %}
            {% if p == page %}
                {# Denoting the page number if this is the active page #} 
                <li class="active page-item">
                    <a class="page-link" href="{% url link page=p%}">{{ p }}</a>
                </li>
            {% else %}
                {# Denoting the page number if NOT the active page #}
                <li class=" page-item">
                    <a class="page-link" href="{% url link page=p%}">{{ p }}</a>
                </li>
            {% endif %}
        {% else %}
            {# If p is None #}
            <li class="disabled page-item"><a href="#"></a></li>
        {% endif %}
    {% endfor %}

</ul>